build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8

exceptions:
  active: true



naming:
  active: true

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: false
  WildcardImport:
    active: true
